/** Common IANA timezones — Africa first, then global. */
export const timezoneOptions = [
  { value: 'Africa/Kampala', label: 'Africa/Kampala (Uganda, EAT)' },
  { value: 'Africa/Kigali', label: 'Africa/Kigali (Rwanda, CAT)' },
  { value: 'Africa/Nairobi', label: 'Africa/Nairobi (Kenya, EAT)' },
  { value: 'Africa/Lagos', label: 'Africa/Lagos (Nigeria, WAT)' },
  { value: 'Africa/Douala', label: 'Africa/Douala (Cameroon, WAT)' },
  { value: 'Africa/Johannesburg', label: 'Africa/Johannesburg (SAST)' },
  { value: 'Africa/Cairo', label: 'Africa/Cairo (Egypt)' },
  { value: 'Africa/Accra', label: 'Africa/Accra (Ghana)' },
  { value: 'Africa/Addis_Ababa', label: 'Africa/Addis Ababa (Ethiopia)' },
  { value: 'Africa/Dar_es_Salaam', label: 'Africa/Dar es Salaam (Tanzania)' },
  { value: 'Africa/Harare', label: 'Africa/Harare (Zimbabwe)' },
  { value: 'Africa/Lusaka', label: 'Africa/Lusaka (Zambia)' },
  { value: 'Africa/Maputo', label: 'Africa/Maputo (Mozambique)' },
  { value: 'Africa/Windhoek', label: 'Africa/Windhoek (Namibia)' },
  { value: 'Africa/Algiers', label: 'Africa/Algiers (Algeria)' },
  { value: 'Africa/Casablanca', label: 'Africa/Casablanca (Morocco)' },
  { value: 'Europe/London', label: 'Europe/London (GMT/BST)' },
  { value: 'Europe/Paris', label: 'Europe/Paris (CET)' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin (CET)' },
  { value: 'America/New_York', label: 'America/New York (EST/EDT)' },
  { value: 'America/Chicago', label: 'America/Chicago (CST/CDT)' },
  { value: 'America/Denver', label: 'America/Denver (MST/MDT)' },
  { value: 'America/Los_Angeles', label: 'America/Los Angeles (PST/PDT)' },
  { value: 'America/Toronto', label: 'America/Toronto' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai (GST)' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata (IST)' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore (SGT)' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo (JST)' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai (CST)' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney (AEST)' },
  { value: 'Pacific/Auckland', label: 'Pacific/Auckland (NZST)' },
  { value: 'UTC', label: 'UTC' },
]

const defaultByCountry: Record<string, string> = {
  Uganda: 'Africa/Kampala',
  Rwanda: 'Africa/Kigali',
  Kenya: 'Africa/Nairobi',
  Nigeria: 'Africa/Lagos',
  Cameroon: 'Africa/Douala',
  Ghana: 'Africa/Accra',
  'South Africa': 'Africa/Johannesburg',
  Egypt: 'Africa/Cairo',
  Tanzania: 'Africa/Dar_es_Salaam',
  Ethiopia: 'Africa/Addis_Ababa',
  Zimbabwe: 'Africa/Harare',
  Zambia: 'Africa/Lusaka',
  Algeria: 'Africa/Algiers',
  Morocco: 'Africa/Casablanca',
  'United Kingdom': 'Europe/London',
  France: 'Europe/Paris',
  Germany: 'Europe/Berlin',
  'United States': 'America/New_York',
  Canada: 'America/Toronto',
  India: 'Asia/Kolkata',
  China: 'Asia/Shanghai',
  Japan: 'Asia/Tokyo',
  Australia: 'Australia/Sydney',
}

export function defaultTimezoneForCountry(country: string): string {
  return defaultByCountry[country] || 'Africa/Kampala'
}
