<?php

/**
 * Master permission catalog for the application.
 *
 * Keep this list aligned with route middleware (permission:...), policies,
 * and frontend access checks. Run `php artisan permissions:sync` after adding
 * new permissions.
 */
return [
    'access_control' => [
        'users.view',
        'users.create',
        'users.edit',
        'users.delete',
        'view_users',
        'create_users',
        'edit_users',
        'delete_users',
        'manage_users',
        'roles.view',
        'roles.create',
        'roles.edit',
        'roles.delete',
        'roles.manage',
        'view_roles',
        'create_roles',
        'edit_roles',
        'delete_roles',
        'manage_roles',
        'permissions.view',
        'permissions.create',
        'permissions.edit',
        'permissions.delete',
        'permissions.manage',
        'view_permissions',
        'assign_permissions',
        'modules.view',
        'modules.manage',
        'manage_modules',
    ],

    'institutions' => [
        'institutions.view',
        'institutions.create',
        'institutions.edit',
        'institutions.delete',
        'institutions.settings',
    ],

    'admissions' => [
        'admissions.view',
        'admissions.manage',
        'admissions.apply',
        'admissions.registry.review',
        'admissions.department.review',
        'admissions.registrar.admit',
        'admissions.finance.verify',
        'admissions.courses.register',
        'admissions.hod.approve',
    ],

    'academics' => [
        'academics.view',
        'academics.create',
        'academics.edit',
        'academics.delete',
        'academics.manage',
        'academics.units.view',
        'academics.units.create',
        'academics.units.edit',
        'academics.units.delete',
        'academics.departments.view',
        'academics.departments.create',
        'academics.departments.edit',
        'academics.departments.delete',
        'academics.programs.view',
        'academics.programs.create',
        'academics.programs.edit',
        'academics.programs.delete',
        'academics.semesters.view',
        'academics.semesters.create',
        'academics.semesters.edit',
        'academics.semesters.delete',
        'academics.subjects.view',
        'academics.subjects.create',
        'academics.subjects.edit',
        'academics.subjects.delete',
        'academics.organization.manage',
    ],

    'operations' => [
        'attendance.view',
        'attendance.manage',
        'results.view',
        'results.manage',
        'fees.view',
        'fees.manage',
        'hr.view',
        'hr.manage',
        'assets.view',
        'assets.manage',
        'notifications.view',
        'notifications.manage',
        'audit.view',
        'audit.manage',
    ],

    'hostel' => [
        'hostel.view',
        'hostel.manage',
        'hostel.allocate',
        'hostel.payments',
        'hostel.maintenance',
        'hostel.clearance',
    ],

    'canteen' => [
        'canteen.view',
        'canteen.manage',
        'canteen.verify',
        'canteen.reports',
    ],

    'character_certificates' => [
        'character_certificates.view',
        'character_certificates.manage',
        'character_certificates.finance_clear',
        'character_certificates.library_clear',
        'character_certificates.issue',
    ],

    'library' => [
        'view_library_menu',
        'manage_library_settings',
        'manage_book_categories',
        'register_books',
        'manage_book_copies',
        'view_books',
        'borrow_books',
        'view_own_borrow_requests',
        'approve_borrow_requests',
        'reject_borrow_requests',
        'issue_books',
        'return_books',
        'view_borrowed_books',
        'view_due_for_return',
        'send_library_reminders',
        'view_overdue_books',
        'manage_library_fines',
        'view_library_reports',
        'view_frequently_signed_books',
        'rate_books',
        'comment_on_books',
    ],

    'timesheets_modern' => [
        'manage_shift_types',
        'manage_teacher_availability',
        'manage_staff_schedules',
        'manage_course_contact_hours',
        'generate_timetable_suggestions',
        'approve_timetable_suggestions',
        'assign_teacher_schedules',
        'view_teacher_schedules',
        'submit_teaching_timesheets',
        'submit_staff_timesheets',
        'approve_timesheets',
        'reject_timesheets',
        'request_timesheet_correction',
        'view_timesheet_reports',
        'view_course_hour_reports',
        'manage_course_hour_plans',
        'manage_timesheet_notifications',
        'view_timesheet_menu',
        'manage_timesheet_categories',
        'create_timesheet_activity',
        'fill_timesheet',
        'manage_own_working_week',
        'view_own_timesheet',
        'edit_own_timesheet',
        'delete_own_timesheet',
        'view_all_timesheets',
        'view_overtime_reports',
        'export_timesheet_reports',
    ],

    'timesheets_legacy' => [
        'timesheets.view_own',
        'timesheets.create_entry',
        'timesheets.submit',
        'timesheets.review',
        'timesheets.report',
        'timesheets.manage',
        'timesheets.manage_shift_types',
        'timesheets.manage_teacher_availability',
        'timesheets.manage_staff_schedules',
        'timesheets.manage_course_contact_hours',
        'timesheets.generate_timetable_suggestions',
        'timesheets.approve_timetable_suggestions',
        'timesheets.assign_teacher_schedules',
        'timesheets.view_teacher_schedules',
        'timesheets.submit_teaching_timesheets',
        'timesheets.submit_staff_timesheets',
        'timesheets.approve_timesheets',
        'timesheets.reject_timesheets',
        'timesheets.view_timesheet_reports',
        'timesheets.view_course_hour_reports',
        'timesheets.manage_course_hour_plans',
    ],

    'letters' => [
        'view_letters_menu',
        'create_letters',
        'edit_letters',
        'edit_awaiting_letters',
        'delete_letters',
        'send_letter_to_editor',
        'forward_letter_to_approver',
        'forward_letter_to_signer',
        'approve_letters',
        'reject_letters',
        'sign_letters',
        'bulk_sign_letters',
        'send_letters',
        'bulk_send_letters',
        'view_awaiting_editing',
        'view_awaiting_approval',
        'view_awaiting_signature',
        'view_ready_to_send_letters',
        'view_sent_letters',
        'print_letters',
        'download_letters',
        'manage_letter_settings',
        'manage_letter_categories',
        'manage_letter_templates',
        'view_announcements',
        'create_announcements',
        'send_announcements',
        'send_whatsapp_announcements',
        'schedule_announcements',
        'manage_announcement_recipients',
        'view_people_menu',
    ],

    'people' => [
        'view_customers',
        'create_customers',
        'edit_customers',
        'delete_customers',
        'view_billers',
        'create_billers',
        'edit_billers',
        'delete_billers',
        'view_suppliers',
        'create_suppliers',
        'edit_suppliers',
        'delete_suppliers',
        'view_students',
        'create_students',
        'edit_students',
        'delete_students',
        'view_teachers',
        'create_teachers',
        'edit_teachers',
        'delete_teachers',
        'view_staff',
        'create_staff',
        'edit_staff',
        'delete_staff',
    ],

    'library_module_alias' => [
        'library.view',
        'library.manage',
    ],
];
